<?php

namespace DF\SondageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	
	public function getCurrentSondage()
	{
		$date = new \DateTime();
		
		$qb = $this->createQueryBuilder('q');
		$qb ->where('q.dateDebut < :date')
			->andWhere('q.dateFin > :date')
			->setParameter('date', $date);
		
		return $qb->getQuery()->getOneOrNullResult();
	}
	
}
