<?php

namespace DF\SondageBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\From;

/**
 * UserVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVoteRepository extends EntityRepository
{
	
	public function getNbVoteByReponse(Reponse $reponse)
	{
		$qb = $this->createQueryBuilder('uv');
		$qb ->select('COUNT(uv)')
			->where('uv.reponse = :reponse')
			->setParameter('reponse', $reponse);
		
		return $qb->getQuery()->getOneOrNullResult();
	}
	
}
