parameters:
#    df_reporters.example.class: DF\ReportersBundle\Example

services:
#    df_reporters.example:
#        class: %df_reporters.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
