<?php

namespace DF\ManageMatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ButRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ButRepository extends EntityRepository
{
}
