security:
    encoders:
        DF\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_REDACTEUR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main: 
            pattern: ^/
            anonymous: true
            provider: main
            form_login: 
                provider: fos_userbundle
            logout: 
                path: fos_user_security_logout
            remember_me: 
                key: %secret%

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
