<?php

namespace DF\JoueurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends EntityRepository
{
	
	public function getJoueursClub($club)
	{
		$qb = $this->createQueryBuilder('j')
			->join('DF\JoueurBundle\Entity\JoueurClub', 'jc')
			->where('jc.joueur = j.id')
			->andWhere('jc.club = :club')
			->setParameter('club' , $club);
		
		return $qb->getQuery()->getResult();
	}
	
}
