<?php

namespace DF\JoueurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JoueurClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurClubRepository extends EntityRepository
{
}
