<?php

namespace DF\StadeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadeRepository extends EntityRepository
{
}
