<?php

namespace DF\EquipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClubEntraineurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubEntraineurRepository extends EntityRepository
{
	
	public function getCurrentClubForEntraineur($entraineur, $saison_id)
	{
		$em = $this->createQueryBuilder();
		
		$em ->select('DF\EquipeBundle\Entity\ClubEntraineur', 'ce')
			->where('ce.entraineur = :entraineur')
			->andWhere('ce.dateDepart IS NULL')
			->andWhere('ce.saison = :saison')
			->setParameter('entraineur', $entraineur)
			->setParameter('saison', $saison_id);
		
		return $em->getQuery()->getOneOrNullResult();
	}
	
}
