<?php

namespace DF\EquipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClubCompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubCompetitionRepository extends EntityRepository
{
}