<?php

namespace DF\EquipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends EntityRepository
{
	
	public function getClubByCompetition($competition, $saison)
	{
		$qb = $this->createQueryBuilder('c')
			->join('DF\EquipeBundle\Entity\ClubCompetition', 'cc')
			->where('cc.competition = :competition')
			->andWhere('cc.saison = :saison')
			->setParameter('competition', $competition)
			->setParameter('saison', $saison);
		
		return $qb->getQuery()->getResult();
	}
	
}
