<?php

namespace DF\EquipeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntraineurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntraineurRepository extends EntityRepository
{
}
