parameters:
#    df_match.example.class: DF\MatchBundle\Example

services:
#    df_match.example:
#        class: %df_match.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
