<?php

namespace DF\MatchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemplacementRepository extends EntityRepository
{
}
